name: Innspill til komponent
description: Send inn innspill til komponenten
title: "[Innspill til komponent]: "
labels: ["feat ✨", "bug 🐛"]
body:
  - type: markdown
    attributes:
      value: |
        Takk for bidraget!
  - type: textarea
    attributes:
      label: Innspill
      description: Beskriv funksjonaliten du ønsker eller feilen du har oppdaget.
